### ISSUE TITLE
Pappy fails to initialize (hangs on startup)

### ISSUE THREAD

**Issue by gabemarshall** [roglew/pappy-proxy#9] opened 2016-08-10 13:45 UTC
Loved your demo at Blackhat! Unfortunately I'm having issues getting pappy up and going. Any idea what could be causing this to happen? I'm running pappy in the following environment.

Mac OS X 10.11.6
Python 2.7.11 (in a virtualenv)

![pappy](https://cloud.githubusercontent.com/assets/2541585/17555836/0d9722f4-5edf-11e6-858d-088dc52c06a1.png)

**Comment by roglew** [comment] 2016-08-10 17:20
Hey, sorry about that. How did you install it? I'll try and reproduce it in a VM

**Comment by gabemarshall** [comment] 2016-08-10 18:16
No worries, I followed the quickstart -- git clone then pip install . within the pappy directory. It installed without issue. I just noticed I'm actually on 10.11.5 -- not sure if that matters, but I'm going to update real quick and see if the issue remains.

**Comment by gabemarshall** [comment] 2016-08-10 19:34
Hmm.. I tried it on my other mac and it works fine. Only difference is I'm using Python 2.7.8

I'll do some more testing to see if I can figure out why the other laptop isn't having the same luck. Feel free to close this issue out if you want.

**Comment by roglew** [comment] 2016-08-10 19:35
Huh, weird. Let me know if you figure anything out and I'll try and take a look at it tonight.

**Comment by roglew** [comment] 2016-08-10 19:36
I'll wait to close it until we look into it a bit because it could still be an issue with pappy

**Comment by roglew** [comment] 2016-08-18 03:03
Alright, I wasn't able to reproduce so I'll close this. If you can reproduce it, let me know and I'll look into the issue. Thanks for trying pappy, I really appreciate it!

**Closed by roglew** 2016-08-18 03:03 UTC

**Comment by gabemarshall** [comment] 2016-09-01 20:16
Hey man, I finally got around to debugging the issue. It turns out the cmd2 library was hanging due to a homewbrew version of pbcopy that I had symlinked. My environment not yours =)

**Comment by roglew** [comment] 2016-09-01 20:29
Awesome, glad you got it figured it out! Thanks for letting me know
